<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\AIFramework3Open\src\AI\AI.csproj" />
    <ProjectReference Include="..\..\..\..\AIFramework3Open\src\AI.LLM\AI.LLM.csproj" />
    <ProjectReference Include="..\..\..\..\AIFramework3Open\src\AI.NLP\AI.NLP.csproj" />
  </ItemGroup>

</Project>
